### ISSUE TITLE
获取会话列表时,报错database is closed

### ISSUE THREAD

**Issue by PaoPaoYo** [openim-sigs/oimws#92]
```
2024-01-24 10:14:22.952	ERROR	[PID:26443]	[interaction/msg_sync.go:73]	get conversation id list failed	{"operationID": "prgpqt8hz1706062461295", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetAllConversationIDList()@78: GetAllConversationIDList failed : sql: database is closed"}
2024-01-24 10:14:22.952	ERROR	[PID:26443]	[interaction/msg_sync.go:63]	loadSeq err	{"operationID": "prgpqt8hz1706062461295", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetAllConversationIDList()@78: GetAllConversationIDList failed : sql: database is closed"}
2024-01-24 10:14:22.952	DEBUG	[PID:26443]	[open_im_sdk/userRelated.go:354]	login success...	{"operationID": "prgpqt8hz1706062461295", "login cost time: ": 0.000692208}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100fb6410]

goroutine 25467 [running]:
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*MsgSyncer).DoListener(0x0, {0x1014af980, 0x14000902ed0})
	/Users/zhanghui/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.0/internal/interaction/msg_sync.go:104 +0x70
created by github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.(*LoginMgr).run in goroutine 25306
	/Users/zhanghui/go/pkg/mod/github.com/openimsdk/openim-s
```

**Comment by FGadvancer** [comment]
related to the issue #93
