### ISSUE TITLE
oimws服务 down了

### ISSUE THREAD

**Issue by zibinlife** [openim-sigs/oimws#93]
```
2024-01-24 10:27:56.685 DEBUG   [PID:17846]     [open_im_sdk/userRelated.go:428]        TriggerCmdLogout server recycle resources success...    {"operationID": "socket close"}
2024-01-24 10:27:56.685 DEBUG   [PID:17846]     [open_im_sdk/userRelated.go:435]        TriggerCmdLogout client success...      {"operationID": "socket close", "isTokenValid": false}
2024-01-24 10:27:56.685 INFO    [PID:17846]     [interaction/msg_sync.go:107]   msg syncer done, sdk logout.....        {"operationID": "f5aiv4bsho1706063236607"}
2024-01-24 10:27:56.685 INFO    [PID:17846]     [interaction/long_conn_mgr.go:288]      heartbeat done sdk logout.....  {"operationID": "f5aiv4bsho1706063236607"}
2024-01-24 10:27:56.685 WARN    [PID:17846]     [interaction/long_conn_mgr.go:283]      heartbeat closed        {"operationID": "1706063239423036851", "heartbeat": "heartbeat done sdk logout....."}
2024-01-24 10:27:56.685 INFO    [PID:17846]     [common/trigger_channel.go:214] conversation done sdk logout.....
2024-01-24 10:27:56.685 INFO    [PID:17846]     [open_im_sdk/userRelated.go:255]        logoutListener done sdk logout.....     {"operationID": "f5aiv4bsho1706063236607"}
2024-01-24 10:27:56.696 ERROR   [PID:17846]     [db/chat_log_model_v3.go:38]    create table seq index failed   {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169045053480960", "error": "sql: database is closed"}
2024-01-24 10:27:56.696 ERROR   [PID:17846]     [db/chat_log_model_v3.go:43]    create table send_time index failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169045053480960", "error": "sql: database is closed"}
2024-01-24 10:27:56.696 ERROR   [PID:17846]     [interaction/msg_sync.go:82]    get group normal seq failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169045053480960", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetConversationNormalMsgSeq()@332: GetConversationNormalMsgSeq: sql: database is closed"}
2024-01-24 10:27:56.697 ERROR   [PID:17846]     [db/chat_log_model_v3.go:38]    create table seq index failed   {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169059017809920", "error": "sql: database is closed"}
2024-01-24 10:27:56.697 ERROR   [PID:17846]     [db/chat_log_model_v3.go:43]    create table send_time index failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169059017809920", "error": "sql: database is closed"}
2024-01-24 10:27:56.697 ERROR   [PID:17846]     [interaction/msg_sync.go:82]    get group normal seq failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169059017809920", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetConversationNormalMsgSeq()@332: GetConversationNormalMsgSeq: sql: database is closed"}
2024-01-24 10:27:56.697 ERROR   [PID:17846]     [db/chat_log_model_v3.go:38]    create table seq index failed   {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169744316551168", "error": "sql: database is closed"}
2024-01-24 10:27:56.699 ERROR   [PID:17846]     [db/chat_log_model_v3.go:43]    create table send_time index failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169744316551168", "error": "sql: database is closed"}
2024-01-24 10:27:56.699 ERROR   [PID:17846]     [interaction/msg_sync.go:82]    get group normal seq failed     {"operationID": "ijpw2wbn81706063276370", "conversationID": "sg_1169744316551168", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetConversationNormalMsgSeq()@332: GetConversationNormalMsgSeq: sql: database is closed"}
2024-01-24 10:27:56.699 ERROR   [PID:17846]     [interaction/msg_sync.go:89]    get notification seq failed     {"operationID": "ijpw2wbn81706063276370", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetNotificationAllSeqs()@43: GetNotificationAllSeqs failed: sql: database is closed"}
2024-01-24 10:27:56.699 ERROR   [PID:17846]     [interaction/msg_sync.go:63]    loadSeq err     {"operationID": "ijpw2wbn81706063276370", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetNotificationAllSeqs()@43: GetNotificationAllSeqs failed: sql: database is closed"}
2024-01-24 10:27:56.699 DEBUG   [PID:17846]     [open_im_sdk/userRelated.go:354]        login success...        {"operationID": "ijpw2wbn81706063276370", "login cost time: ": 0.01426576}
2024-01-24 10:27:56.699 DEBUG   [PID:17846]     [interaction/long_conn_mgr.go:279]      heartbeat start {"operationID": "ijpw2wbn81706063276370", "goroutine ID:": 166435}
2024-01-24 10:27:56.699 DEBUG   [PID:17846]     [interaction/long_conn_mgr.go:171]      readPump start  {"operationID": "ijpw2wbn81706063276370", "goroutine ID:": 166401}
2024-01-24 10:27:56.699 DEBUG   [PID:17846]     [interaction/long_conn_mgr.go:499]      conn start      {"operationID": "1706063280061962243"}
2024-01-24 10:27:56.699 DEBUG   [PID:17846]     [interaction/long_conn_mgr.go:231]      writePump start {"operationID": "ijpw2wbn81706063276370", "goroutine ID:": 166434}
2024-01-24 10:27:56.700 INFO    [PID:17846]     [interaction/long_conn_mgr.go:554]      long conn establish success     {"operationID": "1706063280061962243", "localAddr": "127.0.0.1:48510", "connNum": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb168de]

goroutine 166436 [running]:
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*MsgSyncer).DoListener(0x0, {0xfdb580, 0xc0005400c0})
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.0/internal/interaction/msg_sync.go:104 +0xbe
created by github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.(*LoginMgr).run
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.0/open_im_sdk/userRelated.go:377 +0xae
make: *** [start] Error 2

以上是截取了部分日志，日志上面有 ERROR 错误。供参考！
[oimws.log](https://github.com/openim-sigs/oimws/files/14033627/oimws.log)
```

**Comment by zibinlife** [comment]
> By what means have you deployed this?
> 
> @FGadvancer thinks so u？

I deployed according to the document,   git clone ->make build ->make start.

**Comment by FGadvancer** [comment]
Thank you for bringing this to my attention. Based on the log information you've provided, I've determined that the panic is due to concurrent operations of logging in and logging out caused by websocket disconnection and reconnection, which leads to a crash after reconnection login failures. I will address and fix this issue on https://github.com/openimsdk/openim-sdk-core shortly and implement corresponding protective measures to prevent oimws crashing.

**Comment by FGadvancer** [comment]
Related to the issue https://github.com/openimsdk/openim-sdk-core/issues/507 has been fixed.
